title: "Diode Network"
description: "A privacy-first communication solution"
baseurl: "/diodenetwork-dev-2025" 
url: "https://diodenetwork.io" 
theme: minima   
favicon: "/assets/images/favicon.ico"

markdown: kramdown
